# Generated by Django 3.0.2 on 2020-01-29 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='predictor',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('antibiotic1', models.IntegerField()),
                ('days1', models.IntegerField()),
                ('r1', models.IntegerField()),
                ('antibiotic2', models.IntegerField()),
                ('days2', models.IntegerField()),
                ('r2', models.IntegerField()),
                ('antibiotic3', models.IntegerField()),
                ('days3', models.IntegerField()),
                ('r3', models.IntegerField()),
                ('gender', models.IntegerField()),
                ('pregnancy', models.IntegerField()),
                ('immune_status', models.IntegerField()),
                ('outcome_of_the_treatment', models.IntegerField()),
                ('Rfinal', models.IntegerField()),
            ],
        ),
    ]
