# Generated by Django 3.0.2 on 2020-01-31 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='predictor',
            old_name='Rfinal',
            new_name='age',
        ),
        migrations.RemoveField(
            model_name='predictor',
            name='antibiotic1',
        ),
        migrations.RemoveField(
            model_name='predictor',
            name='antibiotic2',
        ),
        migrations.RemoveField(
            model_name='predictor',
            name='antibiotic3',
        ),
        migrations.RemoveField(
            model_name='predictor',
            name='days1',
        ),
        migrations.RemoveField(
            model_name='predictor',
            name='days2',
        ),
        migrations.RemoveField(
            model_name='predictor',
            name='days3',
        ),
        migrations.RemoveField(
            model_name='predictor',
            name='immune_status',
        ),
        migrations.RemoveField(
            model_name='predictor',
            name='outcome_of_the_treatment',
        ),
        migrations.RemoveField(
            model_name='predictor',
            name='r1',
        ),
        migrations.RemoveField(
            model_name='predictor',
            name='r2',
        ),
        migrations.RemoveField(
            model_name='predictor',
            name='r3',
        ),
        migrations.AddField(
            model_name='predictor',
            name='antibiotic',
            field=models.CharField(default='SOME STRING', max_length=20),
        ),
        migrations.AddField(
            model_name='predictor',
            name='immune',
            field=models.CharField(default='SOME STRING', max_length=20),
        ),
        migrations.AddField(
            model_name='predictor',
            name='infection',
            field=models.CharField(default='SOME STRING', max_length=20),
        ),
        migrations.AddField(
            model_name='predictor',
            name='localion',
            field=models.CharField(default='SOME STRING', max_length=20),
        ),
        migrations.AddField(
            model_name='predictor',
            name='resistance',
            field=models.CharField(default='SOME STRING', max_length=20),
        ),
        migrations.AlterField(
            model_name='predictor',
            name='gender',
            field=models.CharField(default='SOME STRING', max_length=20),
        ),
        migrations.AlterField(
            model_name='predictor',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='predictor',
            name='pregnancy',
            field=models.CharField(default='SOME STRING', max_length=20),
        ),
    ]
