# Generated by Django 3.0.2 on 2020-01-31 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0002_auto_20200131_1512'),
    ]

    operations = [
        migrations.RenameField(
            model_name='predictor',
            old_name='localion',
            new_name='location',
        ),
    ]
