# Generated by Django 3.0.2 on 2020-01-25 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='AntibioticGroup',
            field=models.CharField(default='SOME STRING', max_length=50),
        ),
    ]
