# Generated by Django 2.2.7 on 2020-01-27 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_record_antibioticgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='Day2',
            field=models.CharField(default='SOME STRING', max_length=10),
        ),
        migrations.AddField(
            model_name='record',
            name='Days1',
            field=models.CharField(default='SOME STRING', max_length=10),
        ),
        migrations.AddField(
            model_name='record',
            name='SecondAntibiotic',
            field=models.CharField(default='SOME STRING', max_length=50),
        ),
        migrations.AddField(
            model_name='record',
            name='ag_1',
            field=models.CharField(default='SOME STRING', max_length=50),
        ),
        migrations.AddField(
            model_name='record',
            name='ag_2',
            field=models.CharField(default='SOME STRING', max_length=50),
        ),
        migrations.AddField(
            model_name='record',
            name='ar_1',
            field=models.CharField(default='SOME STRING', max_length=40),
        ),
    ]
