# Generated by Django 2.2.7 on 2020-01-27 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200127_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='PatientId',
            field=models.CharField(default='SOME STRING', max_length=50),
        ),
    ]
