# Generated by Django 2.2.7 on 2020-01-27 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_record_patientid'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='ThirdAntibiotic',
            field=models.CharField(default='SOME STRING', max_length=50),
        ),
        migrations.AddField(
            model_name='record',
            name='ar_2',
            field=models.CharField(default='SOME STRING', max_length=40),
        ),
    ]
