# Generated by Django 2.2.7 on 2020-01-27 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200127_1936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='AntibioticGroup',
        ),
    ]
