# Generated by Django 2.2.7 on 2020-01-27 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_record_antibioticgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='Days3',
            field=models.CharField(default='SOME STRING', max_length=50),
        ),
        migrations.AddField(
            model_name='record',
            name='ar_3',
            field=models.CharField(default='SOME STRING', max_length=40),
        ),
    ]
