# Generated by Django 2.2.7 on 2020-01-27 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20200127_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='age',
            field=models.CharField(default='SOME STRING', max_length=30),
        ),
        migrations.AddField(
            model_name='record',
            name='city',
            field=models.CharField(default='SOME STRING', max_length=40),
        ),
        migrations.AddField(
            model_name='record',
            name='state',
            field=models.CharField(default='SOME STRING', max_length=30),
        ),
    ]
