# Generated by Django 2.2.7 on 2020-01-27 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20200127_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='gender',
            field=models.CharField(default='SOME STRING', max_length=20),
        ),
    ]
