# Generated by Django 2.2.7 on 2020-01-27 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_record_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='pregnancy',
            field=models.CharField(default='SOME STRING', max_length=20),
        ),
    ]
