# Generated by Django 2.2.7 on 2020-01-27 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_record_pregnancy'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='immunestatus',
            field=models.CharField(default='SOME STRING', max_length=10),
        ),
        migrations.AddField(
            model_name='record',
            name='outcome',
            field=models.CharField(default='SOME STRING', max_length=30),
        ),
    ]
