# Generated by Django 2.2.7 on 2020-01-28 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20200127_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='outcome',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='record',
            name='pregnancy',
            field=models.CharField(blank=True, default='SOME STRING', max_length=20),
        ),
    ]
