# Generated by Django 2.2.7 on 2020-01-28 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_record_ag_3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='FirstAntibiotic',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='SecondAntibiotic',
            field=models.CharField(blank=True, default='SOME STRING', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='ThirdAntibiotic',
            field=models.CharField(blank=True, default='SOME STRING', max_length=50, null=True),
        ),
    ]
