# Generated by Django 2.2.7 on 2020-01-28 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20200128_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='FirstAntibiotic',
            field=models.CharField(default='SOME STRING', max_length=50),
        ),
        migrations.AlterField(
            model_name='record',
            name='SecondAntibiotic',
            field=models.CharField(default='SOME STRING', max_length=50),
        ),
        migrations.AlterField(
            model_name='record',
            name='ThirdAntibiotic',
            field=models.CharField(default='SOME STRING', max_length=50),
        ),
        migrations.AlterField(
            model_name='record',
            name='pregnancy',
            field=models.CharField(default='SOME STRING', max_length=20),
        ),
    ]
