# Generated by Django 2.2.7 on 2020-01-28 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20200128_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='pregnancy',
            field=models.CharField(blank=True, default='SOME STRING', max_length=20, null=True),
        ),
    ]
