# Generated by Django 2.2.7 on 2020-01-28 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20200128_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='FirstAntibiotic',
            field=models.CharField(blank=True, default='SOME STRING', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='SecondAntibiotic',
            field=models.CharField(blank=True, default='SOME STRING', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='ThirdAntibiotic',
            field=models.CharField(blank=True, default='SOME STRING', max_length=50, null=True),
        ),
    ]
