# Generated by Django 2.2.7 on 2020-01-28 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20200128_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='Day2',
            field=models.CharField(blank=True, default='SOME STRING', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='Days1',
            field=models.CharField(blank=True, default='SOME STRING', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='Days3',
            field=models.CharField(blank=True, default='SOME STRING', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='PatientId',
            field=models.CharField(blank=True, default='SOME STRING', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='ag_1',
            field=models.CharField(blank=True, default='SOME STRING', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='ag_2',
            field=models.CharField(blank=True, default='SOME STRING', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='ag_3',
            field=models.CharField(blank=True, default='SOME STRING', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='age',
            field=models.CharField(blank=True, default='SOME STRING', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='ar_1',
            field=models.CharField(blank=True, default='SOME STRING', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='ar_2',
            field=models.CharField(blank=True, default='SOME STRING', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='ar_3',
            field=models.CharField(blank=True, default='SOME STRING', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='city',
            field=models.CharField(blank=True, default='SOME STRING', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='gender',
            field=models.CharField(blank=True, default='SOME STRING', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='immunestatus',
            field=models.CharField(blank=True, default='SOME STRING', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='state',
            field=models.CharField(blank=True, default='SOME STRING', max_length=30, null=True),
        ),
    ]
