# Generated by Django 3.0.2 on 2020-01-30 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20200128_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='prerecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PatientId', models.CharField(blank=True, default='SOME STRING', max_length=50, null=True)),
                ('FirstAntibiotic', models.CharField(blank=True, default='SOME STRING', max_length=50, null=True)),
                ('ag_1', models.CharField(blank=True, default='SOME STRING', max_length=50, null=True)),
                ('ar_1', models.CharField(blank=True, default='SOME STRING', max_length=40, null=True)),
                ('SecondAntibiotic', models.CharField(blank=True, default='SOME STRING', max_length=50, null=True)),
                ('ag_2', models.CharField(blank=True, default='SOME STRING', max_length=50, null=True)),
                ('ar_2', models.CharField(blank=True, default='SOME STRING', max_length=40, null=True)),
                ('ThirdAntibiotic', models.CharField(blank=True, default='SOME STRING', max_length=50, null=True)),
                ('ag_3', models.CharField(blank=True, default='SOME STRING', max_length=50, null=True)),
                ('ar_3', models.CharField(blank=True, default='SOME STRING', max_length=40, null=True)),
                ('FourthAntibiotic', models.CharField(blank=True, default='SOME STRING', max_length=50, null=True)),
                ('ag_4', models.CharField(blank=True, default='SOME STRING', max_length=50, null=True)),
                ('ar_4', models.CharField(blank=True, default='SOME STRING', max_length=40, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='record',
            old_name='Days3',
            new_name='FourthAntibiotic',
        ),
        migrations.RemoveField(
            model_name='record',
            name='Day2',
        ),
        migrations.RemoveField(
            model_name='record',
            name='Days1',
        ),
        migrations.RemoveField(
            model_name='record',
            name='outcome',
        ),
        migrations.AddField(
            model_name='record',
            name='ag_4',
            field=models.CharField(blank=True, default='SOME STRING', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='ar_4',
            field=models.CharField(blank=True, default='SOME STRING', max_length=40, null=True),
        ),
    ]
