# Generated by Django 3.0.2 on 2020-01-31 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20200130_2222'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prerecord',
            old_name='ar_1',
            new_name='in2',
        ),
        migrations.RemoveField(
            model_name='prerecord',
            name='PatientId',
        ),
        migrations.RemoveField(
            model_name='prerecord',
            name='ag_1',
        ),
        migrations.RemoveField(
            model_name='prerecord',
            name='ag_2',
        ),
        migrations.RemoveField(
            model_name='prerecord',
            name='ag_3',
        ),
        migrations.RemoveField(
            model_name='prerecord',
            name='ag_4',
        ),
        migrations.RemoveField(
            model_name='prerecord',
            name='ar_2',
        ),
        migrations.RemoveField(
            model_name='prerecord',
            name='ar_3',
        ),
        migrations.RemoveField(
            model_name='prerecord',
            name='ar_4',
        ),
        migrations.RemoveField(
            model_name='record',
            name='ag_1',
        ),
        migrations.RemoveField(
            model_name='record',
            name='ag_2',
        ),
        migrations.RemoveField(
            model_name='record',
            name='ag_3',
        ),
        migrations.RemoveField(
            model_name='record',
            name='ag_4',
        ),
        migrations.AddField(
            model_name='record',
            name='in1',
            field=models.CharField(blank=True, default='SOME STRING', max_length=40, null=True),
        ),
    ]
