# Generated by Django 3.0.2 on 2020-02-01 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_auto_20200131_1255'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prerecord',
            old_name='FirstAntibiotic',
            new_name='Antibiotic',
        ),
        migrations.RemoveField(
            model_name='prerecord',
            name='FourthAntibiotic',
        ),
        migrations.RemoveField(
            model_name='prerecord',
            name='SecondAntibiotic',
        ),
        migrations.RemoveField(
            model_name='prerecord',
            name='ThirdAntibiotic',
        ),
        migrations.RemoveField(
            model_name='prerecord',
            name='in2',
        ),
        migrations.AddField(
            model_name='prerecord',
            name='ag_1',
            field=models.CharField(blank=True, default='SOME STRING', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='prerecord',
            name='age',
            field=models.CharField(blank=True, default='SOME STRING', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='prerecord',
            name='city',
            field=models.CharField(blank=True, default='SOME STRING', max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='prerecord',
            name='gender',
            field=models.CharField(blank=True, default='SOME STRING', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='prerecord',
            name='immunestatus',
            field=models.CharField(blank=True, default='SOME STRING', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='prerecord',
            name='pregnancy',
            field=models.CharField(blank=True, default='SOME STRING', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='prerecord',
            name='state',
            field=models.CharField(blank=True, default='SOME STRING', max_length=30, null=True),
        ),
    ]
