# Generated by Django 3.0.2 on 2020-02-02 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_auto_20200201_1216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prerecord',
            old_name='Antibiotic',
            new_name='antibiotic',
        ),
        migrations.RenameField(
            model_name='prerecord',
            old_name='immunestatus',
            new_name='immune',
        ),
        migrations.RenameField(
            model_name='prerecord',
            old_name='ag_1',
            new_name='infection',
        ),
        migrations.RenameField(
            model_name='prerecord',
            old_name='city',
            new_name='location',
        ),
    ]
