# Generated by Django 3.0.2 on 2020-02-03 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_auto_20200202_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='prerecord',
            name='resistance',
            field=models.CharField(blank=True, default='SOME STRING', max_length=40, null=True),
        ),
    ]
