# Generated by Django 3.0.2 on 2020-02-04 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_approvals'),
    ]

    operations = [
        migrations.DeleteModel(
            name='prerecord',
        ),
        migrations.RemoveField(
            model_name='approvals',
            name='applicantincome',
        ),
        migrations.RemoveField(
            model_name='approvals',
            name='area',
        ),
        migrations.RemoveField(
            model_name='approvals',
            name='coapplicatincome',
        ),
        migrations.RemoveField(
            model_name='approvals',
            name='credithistory',
        ),
        migrations.RemoveField(
            model_name='approvals',
            name='dependants',
        ),
        migrations.RemoveField(
            model_name='approvals',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='approvals',
            name='graduatededucation',
        ),
        migrations.RemoveField(
            model_name='approvals',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='approvals',
            name='loanamt',
        ),
        migrations.RemoveField(
            model_name='approvals',
            name='loanterm',
        ),
        migrations.RemoveField(
            model_name='approvals',
            name='married',
        ),
        migrations.RemoveField(
            model_name='approvals',
            name='selfemployed',
        ),
        migrations.AddField(
            model_name='approvals',
            name='age',
            field=models.CharField(blank=True, default='SOME STRING', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='approvals',
            name='antibiotic',
            field=models.CharField(blank=True, default='SOME STRING', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='approvals',
            name='immunestatus',
            field=models.CharField(blank=True, default='SOME STRING', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='approvals',
            name='infection',
            field=models.CharField(blank=True, default='SOME STRING', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='approvals',
            name='location',
            field=models.CharField(blank=True, default='SOME STRING', max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='approvals',
            name='pregnancy',
            field=models.CharField(blank=True, default='SOME STRING', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='approvals',
            name='resistance',
            field=models.CharField(blank=True, default='SOME STRING', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='approvals',
            name='gender',
            field=models.CharField(blank=True, default='SOME STRING', max_length=20, null=True),
        ),
    ]
