# Generated by Django 3.0.2 on 2020-02-04 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_auto_20200204_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approvals',
            name='resistance',
        ),
    ]
